
pub const NEW_PROJECT_CHILD_WINDOW_SIZE: [f32; 2] = [240.0, 30.0];
pub const CREATE_TEAM_CHILD_WINDOW_SIZE: [f32; 2] = NEW_PROJECT_CHILD_WINDOW_SIZE;
pub const RENAME_TEAM_CHILD_WINDOW_SIZE: [f32; 2] = CREATE_TEAM_CHILD_WINDOW_SIZE;
pub const CREATE_RESOURCE_CHILD_WINDOW_SIZE: [f32; 2] = CREATE_TEAM_CHILD_WINDOW_SIZE;
pub const RENAME_RESOURCE_CHILD_WINDOW_SIZE: [f32; 2] = CREATE_RESOURCE_CHILD_WINDOW_SIZE;
pub const CREATE_TASK_CHILD_WINDOW_SIZE: [f32; 2] = [180.0, 150.0];
pub const UPDATE_TASK_CHILD_WINDOW_SIZE: [f32; 2] = CREATE_TASK_CHILD_WINDOW_SIZE;
pub const CREATE_MILESTONE_CHILD_WINDOW_SIZE: [f32; 2] = [240.0, 70.0];
pub const SET_WORKLOG_CHILD_WINDOW_SIZE: [f32; 2] = [260.0, 100.0];
pub const CREATE_LABEL_CHILD_WINDOW_SIZE: [f32; 2] = [240.0, 70.0];
